//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AutoDetector.rc
//
#define IDD_AutoDetector_Dlg            101
#define IDM_Sample_Config               102
#define IDM_Standard_Config             103
#define IDD_Test_Dlg                    104
#define IDM_All_Deselect                105
#define IDD_Reagent_Dlg                 106
#define IDM_Delete_Sample               107
#define IDD_Sample_Dlg                  108
#define IDD_Standerd_Dlg                109
#define IDD_Analysis_Dlg                110
#define IDD_Maintain_Dlg                111
#define IDC_MainFrame                   128
#define IDR_SettingPress                129
#define IDR_SettingHot                  130
#define IDR_SetingNormal                131
#define IDR_MaxNormal                   132
#define IDR_MaxPress                    133
#define IDD_SampleConfig_Dlg            134
#define IDR_MaxHot                      134
#define IDR_MinNormal                   135
#define IDD_StandardConfig_Dlg          136
#define IDR_MinPress                    136
#define IDR_ResNormal                   137
#define IDR_ResHot                      140
#define IDR_ResPress                    141
#define IDR_ClosePress                  142
#define IDR_CloseHot                    143
#define IDR_CloseNormal                 144
#define IDR_PNG1                        145
#define IDR_MinHot                      145
#define IDD_SampleAreaMan_Dlg           147
#define IDD_ReagentAreaMan_Dlg          148
#define IDD_NewTestConfirm_Dlg          149
#define IDD_TestMonitor_Dlg             150
#define IDI_Plus                        152
#define IDI_PlusDisable                 153
#define IDD_ReagentSelect_Dlg           154
#define IDR_PlusPress                   155
#define IDD_Curve_Dlg                   159
#define IDM_Reagent_Select              180
#define IDM_Reagent_Delete              181
#define IDC_Btn_Setting                 200
#define IDC_Btn_Help                    201
#define IDC_MainTab                     202
#define IDD_Summary_Dlg                 210
#define IDC_Ctrl_SampleArea             212
#define IDC_Title_ShortName             213
#define IDC_Ctrl_ReagentArea            215
#define IDC_Ctrl_IncuArea               217
#define IDC_TestMan_Tab                 1003
#define IDC_GrpTitle_SelectConditions   1004
#define IDC_COMBO_PojectName            1005
#define IDC_Date_ProductFrom            1006
#define IDC_Combo_BatchNum              1007
#define IDC_COMBO_PojectName2           1007
#define IDC_Combo_SampleType            1007
#define IDC_Date_ProductTo              1008
#define IDC_LIST_Reagents               1009
#define IDC_CHECK_HideExpired           1010
#define IDC_Title_ProjectName           1011
#define IDC_Value_NumPrefix             1012
#define IDC_Title_ProductDateFrom       1012
#define IDC_Title_SampleNo              1012
#define IDC_Title_ProductDateTo         1013
#define IDC_Edit_StartConc              1014
#define IDC_Title_List                  1014
#define IDC_Title_ProjectName4          1014
#define IDC_Combox_Type                 1015
#define IDC_Title_ID                    1015
#define IDC_Title_SampleType            1015
#define IDC_Value_Dilution              1016
#define IDC_Data_ID                     1016
#define IDC_Title_ProjectName6          1016
#define IDC_Value_Dept                  1017
#define IDC_Title_BatchNum2             1017
#define IDC_Title_ProjectName7          1017
#define IDC_Title_Operator              1017
#define IDC_Edit_Increament             1018
#define IDC_Data_BatchNum               1018
#define IDC_Data_BatchNum2              1018
#define IDC_Value_Applicant             1019
#define IDC_Title_ProjectName2          1019
#define IDC_Data_ProjectName            1020
#define IDC_Data_ProjectName2           1020
#define IDC_Combox_Serials              1021
#define IDC_Data_ProductDate2           1022
#define IDC_Cancle                      1023
#define IDC_Checkbox_SetDefault         1024
#define IDC_Data__ExpirationDate        1024
#define IDC_Data_ExpirationDate         1024
#define IDC_Data_RatedTestTimes         1025
#define IDC_Data_RemainTimes            1026
#define IDC_ComBox_BatchNum             1027
#define IDC_Title_FirstLoadTime         1027
#define IDC_Spin_Repeation              1028
#define IDC_Data_FirstLoadTime          1028
#define IDC_Title_TestProject           1029
#define IDC_Spin_StartConc              1029
#define IDC_Title_FirstUseTime          1029
#define IDC_Title_BatchNum              1030
#define IDC_Spin_Increament             1030
#define IDC_ComBox_TestProject          1031
#define IDC_SPIN_Dilution               1031
#define IDC_Data_FirstUseTime           1031
#define IDC_Title_ProductDate           1032
#define IDC_Data_ProductDate            1033
#define IDC_Value_ProductDate           1033
#define IDC_Data_Unit                   1033
#define IDC_Title_ExpirationDate        1034
#define IDC_Title_Dilution              1034
#define IDC_Value_ExpirationDate        1035
#define IDC_Title_UpperLimit            1035
#define IDC_Title_RatedTestTimes        1036
#define IDC_Value_RatedTestTimes        1037
#define IDC_Data_UpperLimit             1037
#define IDC_Title_RemainTimes           1038
#define IDC_Value_RemainTimes           1039
#define IDC_Title_LowerLimit            1039
#define IDC_Title_CountOfStdPoints      1040
#define IDC_Data_LowerLimit             1040
#define IDC_Value_CountOfStdPoints      1041
#define IDC_Title_SampleAmount          1041
#define IDC_Title_Unit                  1042
#define IDC_Value_Unit                  1043
#define IDC_Data_SampleAmount           1043
#define IDC_Title_StdPoint              1044
#define IDC_Title_Unit2                 1044
#define IDC_Title_MagneticAmount        1044
#define IDC_Title_StdConc               1045
#define IDC_Value_Unit2                 1045
#define IDC_Data_MagneticAmount         1045
#define IDC_Title_PointA                1046
#define IDC_Title_HRPAmount             1046
#define IDC_Title_PointB                1047
#define IDC_Data_HRPAmount              1047
#define IDC_Title_PointC                1048
#define IDC_Title_Dilution2             1048
#define IDC_Title_PointD                1049
#define IDC_Data_Dilution               1049
#define IDC_Title_PointE                1050
#define IDC_Title_WashTimes             1050
#define IDC_Title_PointF                1051
#define IDC_Data_WashTimes              1051
#define IDC_Title_PointG                1052
#define IDC_Title_WashTimes2            1052
#define IDC_Title_IncubationTime        1052
#define IDC_Title_PointH                1053
#define IDC_Data_WashTimes2             1053
#define IDC_Data_IncubationTime         1053
#define IDC_Title_PointI                1054
#define IDC_Title_ProjectDate2          1054
#define IDC_Title_ProductDate2          1054
#define IDC_Title_PointJ                1055
#define IDC_LIST_ReagentArea            1055
#define IDC_Title_Std8                  1055
#define IDC_Value_PointA                1056
#define IDC_LIST_SampleArea             1056
#define IDC_Data_Std8                   1056
#define IDC_Value_PointB                1057
#define IDC_List_TestConfirm            1057
#define IDC_Value_PointC                1058
#define IDC_Start                       1058
#define IDC_Value_PointD                1059
#define IDC_List_Mornitor               1059
#define IDC_Title_Std9                  1059
#define IDC_Value_PointE                1060
#define IDC_AddRecord_Button            1060
#define IDC_Value_PointF                1061
#define IDC_DeleteRecord_Button         1061
#define IDC_Value_PointG                1062
#define IDC_Modify_Button               1062
#define IDC_Value_PointH                1063
#define IDC_Data_Std9                   1063
#define IDC_Value_PointI                1064
#define IDC_GrpTitle_Details            1064
#define IDC_Value_PointJ                1065
#define IDC_LIST_Standerd               1065
#define IDC_GrpTitle_StandardInfo       1066
#define IDC_Title_Std10                 1066
#define IDC_LIST_Curve                  1066
#define IDC_GrpTitle_TestConfigInfo     1067
#define IDC_Data_Std10                  1067
#define IDC_Title_Repeation             1068
#define IDC_Title_StdPointCount         1068
#define IDC_Edit_Repeation              1069
#define IDC_Data_StdPointCount          1069
#define IDC_List_TestConfig             1070
#define IDC_Title_Std1                  1070
#define IDC_OK                          1071
#define IDC_Data_Std1                   1071
#define IDC_CANCEL                      1072
#define IDC_Title_Std2                  1072
#define IDC_Float_Button                1073
#define IDC_STATIC_Reagent              1073
#define IDC_Data_Std2                   1073
#define IDC_Title_NumPrefix             1074
#define IDC_Title_Std3                  1074
#define IDC_Float_EditCtrl              1075
#define IDC_Title_Serials               1075
#define IDC_Data_Std3                   1075
#define IDC_Float_SpinButton            1076
#define IDC_Title_Type                  1076
#define IDC_Title_Std4                  1076
#define IDC_Float_Combox                1077
#define IDC_Title_Dept                  1077
#define IDC_Data_Std4                   1077
#define IDC_Title_Applicant             1078
#define IDC_Title_Std5                  1078
#define IDC_Title_Project               1079
#define IDC_Data_Std5                   1079
#define IDC_ConfigList                  1080
#define IDC_Title_Std6                  1080
#define IDC_Checkbox_SetTheoryConc      1081
#define IDC_Data_Std6                   1081
#define IDC_Title_ApplyDate             1082
#define IDC_Title_Std7                  1082
#define IDC_Date_ApplyDate              1083
#define IDC_Data_Std7                   1083
#define IDC_Title_StartConc             1085
#define IDC_Title_TestDate              1085
#define IDC_Title_Increament            1086
#define IDC_Date_TestDateFrom           1086
#define IDC_Static_Sample               1087
#define IDC_Date_TestDateTo             1087
#define IDC_Static_Test                 1088
#define IDC_Title_TildeSymbol           1088
#define IDC_Static_ListView             1089
#define IDC_LIST_CurveData              1089
#define IDC_Listbox_Project             1090
#define IDC_Float_DateCtrl              1091
#define IDC_GrpTitle_CurveDetails       1091
#define IDC_Title_CurveData             1092
#define IDC_Title_CurveDiagram          1093
#define IDC_Static_CurveDrawing         1094
#define IDC_Edit_SampleNo               1096
#define IDC_EDIT2                       1097
#define IDC_Edit_Dept                   1097
#define IDC_EDIT3                       1098
#define IDC_Edit_Applicant              1098
#define IDC_EDIT4                       1099
#define IDC_Edit_Operator               1099
#define IDC_LIST1                       1100
#define IDC_List_Sample                 1100
#define IDC_Check_Spline                1101
#define IDC_Check_FourParams            1102
#define IDC_Raido_LogScale              1103
#define IDC_Raido_ActualScale           1104
#define IDC_Print_Button                1105
#define IDR_Banner_Right                8005
#define IDR_Banner_Middle               8007
#define IDR_Banner_Left                 8008

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        160
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1106
#define _APS_NEXT_SYMED_VALUE           113
#endif
#endif
